/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import ModelView.Listas;

/**
 *
 * @author gabou
 */
public class Frutas extends javax.swing.JFrame {
    public ArrayList<String> frutas;
    Listas li = new Listas();
    
    /**
     * Creates new form Frutas
     */
    public Frutas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Manzana = new javax.swing.JRadioButton();
        Naranja = new javax.swing.JRadioButton();
        Banano = new javax.swing.JRadioButton();
        Uva = new javax.swing.JRadioButton();
        Pera = new javax.swing.JRadioButton();
        Sandia = new javax.swing.JRadioButton();
        Papaya = new javax.swing.JRadioButton();
        Guayaba = new javax.swing.JRadioButton();
        Mandarina = new javax.swing.JRadioButton();
        Fresa = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elija las frutas que desee ordenar");

        Manzana.setText("Manzana");
        Manzana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManzanaActionPerformed(evt);
            }
        });

        Naranja.setText("Naranja");
        Naranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaranjaActionPerformed(evt);
            }
        });

        Banano.setText("Banano");

        Uva.setText("Uva");
        Uva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UvaActionPerformed(evt);
            }
        });

        Pera.setText("Pera");

        Sandia.setText("Sandia");

        Papaya.setText("Papaya");
        Papaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapayaActionPerformed(evt);
            }
        });

        Guayaba.setText("Guayaba");

        Mandarina.setText("Mandarina");

        Fresa.setText("Fresa");

        jButton1.setText("Agragar al carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Manzana)
                                    .addComponent(Sandia))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pera)
                                    .addComponent(Papaya))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Naranja)
                                    .addComponent(Guayaba))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Banano)
                                        .addGap(38, 38, 38)
                                        .addComponent(Uva))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Mandarina)
                                        .addGap(18, 18, 18)
                                        .addComponent(Fresa))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButton1)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manzana)
                    .addComponent(Pera)
                    .addComponent(Naranja)
                    .addComponent(Banano)
                    .addComponent(Uva))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sandia)
                    .addComponent(Papaya)
                    .addComponent(Guayaba)
                    .addComponent(Mandarina)
                    .addComponent(Fresa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManzanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManzanaActionPerformed

    private void NaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NaranjaActionPerformed

    private void UvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UvaActionPerformed

    private void PapayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PapayaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if(Manzana.isSelected()){
                frutas.add("Manzana");
            }
            if(Pera.isSelected()){
                frutas.add("Pera");
            }
            if(Naranja.isSelected()){
                frutas.add("Naranja");
            }
            if(Banano.isSelected()){
                frutas.add("Banano");
            }
            if(Uva.isSelected()){
                frutas.add("Uva");
            }
            if(Sandia.isSelected()){
                frutas.add("Sandia");
            }
            if(Papaya.isSelected()){
                frutas.add("Papaya");
            }
            if(Guayaba.isSelected()){
                frutas.add("Guayaba");
            }
            if(Mandarina.isSelected()){
                frutas.add("Mandarina");
            }
            if(Fresa.isSelected()){
                frutas.add("Fresa");
            }

            li.fruta(frutas);
        }
        catch(java.lang.NullPointerException ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Frutas.this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Banano;
    private javax.swing.JRadioButton Fresa;
    private javax.swing.JRadioButton Guayaba;
    private javax.swing.JRadioButton Mandarina;
    private javax.swing.JRadioButton Manzana;
    private javax.swing.JRadioButton Naranja;
    private javax.swing.JRadioButton Papaya;
    private javax.swing.JRadioButton Pera;
    private javax.swing.JRadioButton Sandia;
    private javax.swing.JRadioButton Uva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
