/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ModelView.Listas;
import java.util.ArrayList;

/**
 *
 * @author gabou
 */
public class Verduras extends javax.swing.JFrame {
    public ArrayList<String> verduras;
    Listas li = new Listas();
    /**
     * Creates new form Verduras
     */
    public Verduras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lechuga = new javax.swing.JRadioButton();
        Remolacha = new javax.swing.JRadioButton();
        Aguacate = new javax.swing.JRadioButton();
        Tomate = new javax.swing.JRadioButton();
        Espinaca = new javax.swing.JRadioButton();
        Zanahoria = new javax.swing.JRadioButton();
        Alverja = new javax.swing.JRadioButton();
        Cebolla = new javax.swing.JRadioButton();
        Papa = new javax.swing.JRadioButton();
        Yuca = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elija las verduras que desee ordenar");

        Lechuga.setText("Lechuga");
        Lechuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LechugaActionPerformed(evt);
            }
        });

        Remolacha.setText("Remolacha");

        Aguacate.setText("Aguacate");
        Aguacate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguacateActionPerformed(evt);
            }
        });

        Tomate.setText("Tomate");

        Espinaca.setText("Espinaca");
        Espinaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspinacaActionPerformed(evt);
            }
        });

        Zanahoria.setText("Zanahoria");

        Alverja.setText("Alverja");

        Cebolla.setText("Cebolla");

        Papa.setText("Papa");
        Papa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapaActionPerformed(evt);
            }
        });

        Yuca.setText("yuca");

        jButton1.setText("Agragar al carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lechuga)
                                    .addComponent(Remolacha))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tomate)
                                    .addComponent(Aguacate))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Espinaca)
                                    .addComponent(Zanahoria))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cebolla)
                                    .addComponent(Alverja))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Yuca)
                            .addComponent(Papa))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lechuga)
                    .addComponent(Tomate)
                    .addComponent(Espinaca)
                    .addComponent(Cebolla)
                    .addComponent(Papa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Remolacha)
                    .addComponent(Aguacate)
                    .addComponent(Zanahoria)
                    .addComponent(Alverja)
                    .addComponent(Yuca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LechugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LechugaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LechugaActionPerformed

    private void AguacateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguacateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AguacateActionPerformed

    private void EspinacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspinacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspinacaActionPerformed

    private void PapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PapaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            if(Lechuga.isSelected()){
                verduras.add("Lechuga");
            }
            if(Tomate.isSelected()){
                verduras.add("Tomate");
            }
            if(Espinaca.isSelected()){
                verduras.add("Espinaca");
            }
            if(Cebolla.isSelected()){
                verduras.add("Cebolla");
            }
            if(Papa.isSelected()){
                verduras.add("Papa");
            }
            if(Remolacha.isSelected()){
                verduras.add("Remolacha");
            }
            if(Aguacate.isSelected()){
                verduras.add("Aguacate");
            }
            if(Zanahoria.isSelected()){
                verduras.add("Zanahoria");
            }
            if(Alverja.isSelected()){
                verduras.add("Alverja");
            }
            if(Yuca.isSelected()){
                verduras.add("Yuca");
            }

            li.verdura(verduras);
        }
        catch(java.lang.NullPointerException ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Verduras.this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verduras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verduras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aguacate;
    private javax.swing.JRadioButton Alverja;
    private javax.swing.JRadioButton Cebolla;
    private javax.swing.JRadioButton Espinaca;
    private javax.swing.JRadioButton Lechuga;
    private javax.swing.JRadioButton Papa;
    private javax.swing.JRadioButton Remolacha;
    private javax.swing.JRadioButton Tomate;
    private javax.swing.JRadioButton Yuca;
    private javax.swing.JRadioButton Zanahoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
